// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategory = "categories"

// Category mapped from table <categories>
type Category struct {
	CategoryID  int32  `gorm:"column:categoryId;primaryKey;autoIncrement:true" json:"categoryId"`
	Title       string `gorm:"column:title;not null" json:"title"`
	OrderNumber int32  `gorm:"column:orderNumber;not null" json:"orderNumber"`
	StatusID    int32  `gorm:"column:statusId;not null" json:"statusId"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
