// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNews = "news"

// News mapped from table <news>
type News struct {
	NewsID          int32     `gorm:"column:newsId;primaryKey;autoIncrement:true" json:"newsId"`
	Title           string    `gorm:"column:title;not null" json:"title"`
	Foreword        string    `gorm:"column:foreword;not null" json:"foreword"`
	Content         string    `gorm:"column:content" json:"content"`
	PublicationDate time.Time `gorm:"column:publicationDate;not null" json:"publicationDate"`
	CategoryID      int32     `gorm:"column:categoryId;not null" json:"categoryId"`
	TagIds          string    `gorm:"column:tagIds" json:"tagIds"`
	CreatedAt       time.Time `gorm:"column:createdAt;not null;default:now()" json:"createdAt"`
	StatusID        int32     `gorm:"column:statusId;not null" json:"statusId"`
}

// TableName News's table name
func (*News) TableName() string {
	return TableNameNews
}
