// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStatus = "statuses"

// Status mapped from table <statuses>
type Status struct {
	StatusID int32 `gorm:"column:statusId;primaryKey" json:"statusId"`
}

// TableName Status's table name
func (*Status) TableName() string {
	return TableNameStatus
}
