env: "local"

db:
  host: "localhost"
  port: 5432
  sslmode: "disable"
  timeout: 4s
  idle_timeout: 60s
  max_pool_size: 10

http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s
  server_port: "8080"
